name: My Custom Action
description: A custom action written in JavaScript
author: Your Name
inputs:
  name:
    description: 'The name to greet'
    required: true
    default: 'World'
outputs:
  message:
    description: 'The greeting message'
runs:
  using: 'node12'
  main: './index.js'
