name: Console Log

on:
  push:
    branches: [ main ]

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Console Log
        uses: ./.my-custom-action
        with:
          message: 'Hello World!'

