name: My GitHub Action

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run my script
      run: |
        echo 'Hello World' > output.txt
