name: Save Output

on: [push]

jobs:
  save-output:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello World' > output.txt
      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt

