name: Open Repository Dialog

on:
  repository_dispatch:
    types: [open-repository]
  workflow_dispatch:

jobs:
  open-dialog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Open dialog
        run: node .scripts/main.js
        env:
          LOG_FILE_PATH: ${{ env.LOG_FILE_PATH }}

