name: Show Prompt on Repository Open

on:
  repository_dispatch:
    types: open-repository

jobs:
  show-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Show prompt
      run: node .scripts/prompt.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMITTER_NAME: "AdrianRi99"
        COMMITTER_EMAIL: "adrian11820@gmail.com"
        AUTHOR_NAME: "AdrianRi99"
        AUTHOR_EMAIL: "adrian11820@gmail.com"
    - name: Write to log file
      uses: octokit/request-action@v2.x
      with:
        method: PUT
        url: https://api.github.com/repos/AdrianRi99/TicTacToe/contents/log.txt
        headers: |
          {
            "Authorization": "token ${{ secrets.GITHUB_TOKEN }}",
            "Content-Type": "application/json"
          }
        body: |
          {
            "message": "Add text to log file",
            "committer": {
              "name": "<COMMITTER_NAME>",
              "email": "<COMMITTER_EMAIL>"
            },
            "author": {
              "name": "<AUTHOR_NAME>",
              "email": "<AUTHOR_EMAIL>"
            },
            "content": "$(echo ${{ secrets.TEXT }} | base64)",
            "branch": "main"
          }
