name: Dispatch Event on Repository Open

on:
  repository_dispatch:
    types: [open-repository]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: open-repository
