name: Show Prompt on Repository Open

on:
  repository_dispatch:
    types: open-repository

jobs:
  show-prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Show prompt
      uses: wei/prompt@v1.0.1
      with:
        message: "Enter your text:"
        variable: text
    - name: Write to log file
      uses: octokit/request-action@v2.x
      with:
        method: PUT
        url: https://api.github.com/repos/AdrianRi99/TicTacToe.git/contents/log.txt
        headers: |
          {
            "Authorization": "token ${{ secrets.GITHUB_TOKEN }}",
            "Content-Type": "application/json"
          }
        body: |
          {
            "message": "Add text to log file",
            "committer": {
              "name": "AdrianRi99",
              "email": "adrian11820@gmail.com"
            },
            "author": {
              "name": "AdrianRi99",
              "email": "adrian11820@gmail.com"
            },
            "content": "$(echo ${{ secrets.TEXT }} | base64)",
            "branch": "main"
          }
