name: Android Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19.0.2+7
      uses: actions/setup-java@v2
      with:
        java-version:  19.0.2+7
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Run Unit Tests and Save Log
      run: ./gradlew testDebugUnitTest --console=plain > test.log
      continue-on-error: true

    - name: Save Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest
