name: Android Unit Tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11.0.15'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build --console=plain > build.log

    - name: Run unit tests
      run: ./gradlew test --console=plain >> build.log

    - name: Save build log
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: build.log
