name: Run tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.15'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build and test
      run: ./gradlew clean build test > build.log 2>&1 || true
    - name: Save build output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: build.log
    - name: Save test output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-log
        path: app/build/test-results/testDebugUnitTest/*.xml
