name: Android Kotlin Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.15
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Save Test Results to Log
      run: |
        echo "========== Test Results =========="
        cat app/build/test-results/testDebugUnitTest/*.xml > test.log
        cat test.log
