name: Android CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.15
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build App
      run: ./gradlew build > build_output.log 2>&1
      continue-on-error: true

    - name: Run Unit Tests
      run: ./gradlew test > test_output.log 2>&1
      continue-on-error: true

    - name: Upload Build Log
      uses: actions/upload-artifact@v2
      with:
        name: Build Log
        path: build_output.log

    - name: Upload Test Log
      uses: actions/upload-artifact@v2
      with:
        name: Test Log
        path: test_output.log
