name: Run Unit Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.15
          
      - name: Build with Gradle
        run: ./gradlew build --console=plain > build.log 2>&1
        
      - name: Run Unit Tests
        run: ./gradlew test --console=plain >> build.log 2>&1

      - name: Upload Build Log
        uses: actions/upload-artifact@v2
        with:
          name: Build Log
          path: build.log
